package com.brandoo.repository;

import com.brandoo.model.Category;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Repository
public interface CategoryRepository extends JpaRepository<Category, java.lang.Integer> {

}