package com.brandoo.controller;

import com.brandoo.model.OrderItem;
import com.brandoo.service.OrderItemService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@RestController
@RequestMapping("/orderitem/")
public class OrderItemController implements CrudController<OrderItem,java.lang.Integer>{

    @Autowired
    private OrderItemService service;

    @Override
    public ResponseEntity<OrderItem> create(@RequestBody OrderItem entity) {
    	
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<OrderItem> update(@RequestBody OrderItem entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<OrderItem>> read(
            @RequestBody OrderItem entity,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.read(entity,pageable));
    }

    @Override
    public ResponseEntity<OrderItem> readOne(@PathVariable("id") java.lang.Integer primaryKey) {
        return ResponseEntity.ok(service.readOne(primaryKey));
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        service.delete(primaryKey);
    }
}