package com.brandoo.service;

import com.brandoo.model.Account;
import com.brandoo.repository.AccountRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class AccountService implements CrudService<Account,java.lang.Integer> {

    @Autowired
    private AccountRepository repository;

    @Override
    public Account create(Account entity) {
        return repository.save(entity);
    }

    @Override
    public Account update(Account entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Account> read(Account entity, Pageable pageable) {
        Example<Account> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Account readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}