package com.brandoo.service;

import com.brandoo.model.Brand;
import com.brandoo.repository.BrandRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class BrandService implements CrudService<Brand,java.lang.Integer> {

    @Autowired
    private BrandRepository repository;

    @Override
    public Brand create(Brand entity) {
        return repository.save(entity);
    }

    @Override
    public Brand update(Brand entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Brand> read(Brand entity, Pageable pageable) {
        Example<Brand> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Brand readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}