package com.brandoo.service;

import com.brandoo.model.Category;
import com.brandoo.repository.CategoryRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class CategoryService implements CrudService<Category,java.lang.Integer> {

    @Autowired
    private CategoryRepository repository;

    @Override
    public Category create(Category entity) {
        return repository.save(entity);
    }

    @Override
    public Category update(Category entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Category> read(Category entity, Pageable pageable) {
        Example<Category> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Category readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}