package com.brandoo.service;

import com.brandoo.model.IdGen;
import com.brandoo.repository.IdGenRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class IdGenService implements CrudService<IdGen,java.lang.Integer> {

    @Autowired
    private IdGenRepository repository;

    @Override
    public IdGen create(IdGen entity) {
        return repository.save(entity);
    }

    @Override
    public IdGen update(IdGen entity) {
        return repository.save(entity);
    }

    @Override
    public Page<IdGen> read(IdGen entity, Pageable pageable) {
        Example<IdGen> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public IdGen readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}