package com.brandoo.service;

import com.brandoo.model.ItemOrder;
import com.brandoo.repository.ItemOrderRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class ItemOrderService implements CrudService<ItemOrder,java.lang.Integer> {

    @Autowired
    private ItemOrderRepository repository;

    @Override
    public ItemOrder create(ItemOrder entity) {
        return repository.save(entity);
    }

    @Override
    public ItemOrder update(ItemOrder entity) {
        return repository.save(entity);
    }

    @Override
    public Page<ItemOrder> read(ItemOrder entity, Pageable pageable) {
        Example<ItemOrder> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public ItemOrder readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}