package com.brandoo.service;

import com.brandoo.model.Item;
import com.brandoo.repository.ItemRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class ItemService implements CrudService<Item,java.lang.Integer> {

    @Autowired
    private ItemRepository repository;

    @Override
    public Item create(Item entity) {
        return repository.save(entity);
    }

    @Override
    public Item update(Item entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Item> read(Item entity, Pageable pageable) {
        Example<Item> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Item readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}