package com.brandoo.service;

import com.brandoo.model.OrderStatus;
import com.brandoo.repository.OrderStatusRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class OrderStatusService implements CrudService<OrderStatus,java.lang.Integer> {

    @Autowired
    private OrderStatusRepository repository;

    @Override
    public OrderStatus create(OrderStatus entity) {
        return repository.save(entity);
    }

    @Override
    public OrderStatus update(OrderStatus entity) {
        return repository.save(entity);
    }

    @Override
    public Page<OrderStatus> read(OrderStatus entity, Pageable pageable) {
        Example<OrderStatus> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public OrderStatus readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}