package com.brandoo.service;

import com.brandoo.model.Order;
import com.brandoo.repository.OrderRepository;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class OrderService implements CrudService<Order,java.lang.Integer> {

    @Autowired
    private OrderRepository repository;

    @Override
    public Order create(Order entity) {
        return repository.save(entity);
    }

    @Override
    public Order update(Order entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Order> read(Order entity, Pageable pageable) {
        Example<Order> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }  
    public List<Order> findAll(PageRequest pageRequest){
        Page<Order> recordsPage = repository.findAll(pageRequest);
        return recordsPage.getContent();
      }

    @Override
    public Order readOne(java.lang.Integer primaryKey) {
        return repository.findById(primaryKey).get();
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}