package com.brandoo.service;

import com.brandoo.model.OrderItem;
import com.brandoo.repository.OrderItemRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class OrderItemService implements CrudService<OrderItem,java.lang.Integer> {

    @Autowired
    private OrderItemRepository repository;

    @Override
    public OrderItem create(OrderItem entity) {
        return repository.save(entity);
    }

    @Override
    public OrderItem update(OrderItem entity) {
        return repository.save(entity);
    }

    @Override
    public Page<OrderItem> read(OrderItem entity, Pageable pageable) {
        Example<OrderItem> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public OrderItem readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}