package com.brandoo.service;

import com.brandoo.model.Role;
import com.brandoo.repository.RoleRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class RoleService implements CrudService<Role,java.lang.Integer> {

    @Autowired
    private RoleRepository repository;

    @Override
    public Role create(Role entity) {
        return repository.save(entity);
    }

    @Override
    public Role update(Role entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Role> read(Role entity, Pageable pageable) {
        Example<Role> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Role readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}