package com.brandoo.service;

import com.brandoo.model.SizeRange;
import com.brandoo.repository.SizeRangeRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class SizeRangeService implements CrudService<SizeRange,java.lang.Integer> {

    @Autowired
    private SizeRangeRepository repository;

    @Override
    public SizeRange create(SizeRange entity) {
        return repository.save(entity);
    }

    @Override
    public SizeRange update(SizeRange entity) {
        return repository.save(entity);
    }

    @Override
    public Page<SizeRange> read(SizeRange entity, Pageable pageable) {
        Example<SizeRange> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public SizeRange readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}