package com.brandoo.service;

import com.brandoo.model.Status;
import com.brandoo.repository.StatusRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Nov 7, 2022, 9:05:57 AM
*/
@Service
public class StatusService implements CrudService<Status,java.lang.Integer> {

    @Autowired
    private StatusRepository repository;

    @Override
    public Status create(Status entity) {
        return repository.save(entity);
    }

    @Override
    public Status update(Status entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Status> read(Status entity, Pageable pageable) {
        Example<Status> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Status readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}